### ISSUE TITLE
Method not found (latest nuget)

### ISSUE THREAD

**Issue by rohimma** [ezet/evelib#74]
System.MissingMethodException: Method not found: 'Void eZet.EveLib.Core.Util.HttpRequestHelper.AddPostData(System.Net.HttpWebRequest, System.String)'.
   at eZet.EveLib.EveAuthModule.EveAuth.<AuthenticateAsync>d__14.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

**Comment by ezet** [comment]
Please provide me with the code/method you are using to produce this.

**Comment by rohimma** [comment]
AuthResponse response = await eveAuth.AuthenticateAsync("my key", "response code from ccp");

**Comment by ezet** [comment]
Which version of EveLib.Core are you using?

**Comment by rohimma** [comment]
why didnt it show up in the update tab... i did an update again and now it works..

**Comment by ezet** [comment]
I have no idea. Maybe your project or nuget settings? Checking the dependencies for newest EveAuth:
Dependencies
Newtonsoft.Json (>= 8.0.2)
eZet.EveLib.Core (>= 3.0.2.1)
