### ISSUE TITLE
EveXML: SkillTraining StartTime and EndTime always MinDate

### ISSUE THREAD

**Issue by Beatlegger** [ezet/evelib#86]
I think the reason is that the attributes:
```
[XmlElement("StartTime")]
[XmlElement("EndTime")]
```
Should look like:
```
[XmlElement("trainingStartTime")]
[XmlElement("trainingEndTime")]
```

Documentation: [Eve Online Developer Documentation](https://eveonline-third-party-documentation.readthedocs.org/en/latest/xmlapi/char_skillintraining/)

**Comment by ezet** [comment]
Thanks, I'll have a look tonight.
